---
- name: Install supervisor
  when: supervisor_uninstall == false
  block:
    - name: Install
      ansible.builtin.include_tasks: install.yml

    - name: Setup
      ansible.builtin.include_tasks: setup.yml

- name: Uninstall supervisor
  when: supervisor_uninstall == true
  block:
    - name: Clean
      ansible.builtin.include_tasks: clean.yml

    - name: Uninstall
      ansible.builtin.include_tasks: uninstall.yml
