---
- name: Ensure that packages are uninstalled
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    autoremove: "{{ supervisor_autoremove }}"
    purge: "{{ supervisor_purge }}"
    state: absent
  loop: "{{ supervisor_packages }}"
